### PR TITLE
Fix: Bring lockfile up to date

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Your lockfile is not up to date.

This patch fixes this.

### CODE REVIEW

**Review by jdisanti — APPROVED** [review]
Thank you!

**Comment by matthiasbeyer** [comment]
Do you think this is worth a patch release?

**Comment by jdisanti** [comment]
It seems to be working with `cargo install --locked cargo-check-external-types`, so I don't really see a good reason to push out a release at the moment.

**Comment by matthiasbeyer** [comment]
I found this because I was not able to build this crate with nix because of the out-of-date lockfile. But well, that's only a portion of your users and they all can build from master (which is what I am doing right now)... so :shrug: fine with me. :+1:

**Pull request merged**
